name: Run BackstopJS test cases # Name of the action
on:
  push:
    branches:
    - main

jobs:
  build:
    name: backstop reference
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/checkout@v3
      - name: Download previous artifact
        uses: actions/github-script@v7
        env:
          WORKFLOW_FILENAME: visual.yml
          ARTIFACT_NAME: backstop_references
          ARTIFACT_FILENAME: backstop_references.zip
          UNZIP_DIR: .
        with:
          script: |
            const pathToScript = '${{ github.workspace }}/scripts/download-previous-artifact.js';
            const script = await import(pathToScript);
            await script.default({ github, context, core });
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install project dependecies and playwright
        run: npm install &&  npx playwright install
      # - name: Generate config file
      #   run: npm run backstop:generate
      # - name: Create reference screenshot from source site
      #   run: npm run backstop:reference
      - name: Run the test(It will take the screenshot of the given site and will test against reference screenshot)
        run: npm run backstop:test
      - name: Create Artifacts
        run: |
          mkdir -p artifacts
          cp -r backstop_data artifacts/
          cp -r public artifacts/
          cp -r reports artifacts/
      - name: Upload references data
        uses: actions/upload-artifact@v4
        with:
          name: backstop_references
          path: artifacts
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
