name: Run BackstopJS test cases # Name of the action
on:
  push:
    branches:
    - main

jobs:
  install_references:
    name: create backstop reference
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install project dependecies and playwright
        run: npm install &&  npx playwright install
      # - name: Generate config file
      #   run: npm run backstop:generate
      - name: Create reference screenshot from source site
        run: npm run backstop:reference
      - name: Create Artifacts
        run: |
          mkdir -p artifacts
          cp -r backstop_data artifacts/
          cp -r public artifacts/
      - name: Upload references data
        uses: actions/upload-artifact@v4
        with:
          name: backstop_references
          path: artifacts
  run_tests:
    name: run backstop tests
    needs: install_references
    runs-on: ubuntu-latest
    steps:
      - name: Download references data
        uses: actions/download-artifact@v4
        with:
          name: backstop_references
      - name: Run the test(It will take the screenshot of the given site and will test against reference screenshot)
        run: npm run backstop:test
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}